server:
  http_listen_port: 9080
  http_listen_address: 0.0.0.0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://testing.mt2h.cl/loki/loki/api/v1/push

scrape_configs:
  #- job_name: journal
  #  journal:
  #    max_age: 12h
  #    labels:
  #      job: docker/systemd-journal
  #  relabel_configs:
  #    - source_labels: ['__journal__systemd_unit']
  #      target_label: 'unit'
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: docker/varlogs
      __path__: /var/log/*log
